### ISSUE TITLE
Firebase Cloud Messaging

### ISSUE THREAD

**Issue by francesco-hayes** [nuxt-community/firebase-module#114]
I currently have everything set up as described in the documentation with the service worker being generated by the plugin. However, after I get the user's permission and I try to receive their token, I receive this error:

`DOMException: Registration failed - push service not available`

I can't seem to get around it... Anyone else encounter something similar or manage to get Cloud Messaging working with this plugin?

Thank you!

**Comment by lupas** [comment]
Hi @francesco-hayes 

Does not sound like an error that would be specific to this module.. What browser/version are you using?

If you have a look at the [demo](https://github.com/lupas/nuxt-fire-demo), you can see that the token is successfully received.

Maybe the code in the demo can help you?

**Comment by francesco-hayes** [comment]
Thank you @lupas 

However, I have tried the demo before but I tried again and it still didn't work. It didn't work on the actual demo site either. 

I am using Brave 1.4.96, which is currently on Chrome 80. I tried it on the most recent version of Firefox and received an error; however, it was worded as so, "The Notification permission may only be requested from inside a short running user-generated event handler."

Any thoughts? Did the demo work for you recently?

**Comment by lupas** [comment]
So when I go to the [demo site](https://nuxt-fire-demo.firebaseapp.com/) and then to `Firebase Messaging`, the following happens:

1. I click start listener
2. I click Request Permission
3. A Popup asks me to give permission to this site, I say "yep"
4. I click Get ID Token
5. The token appears

Tested right now on Chrome 80 Official Build.

<img width="1440" alt="Screenshot 2020-03-10 at 20 23 51" src="https://user-images.githubusercontent.com/4020037/76351075-26820000-630d-11ea-9c79-9f9df8751f05.png">

Since the demo page also does not work for you, I assume it is something in your setup. But then again, messaging always behaved a bit depending on the browser...

**Comment by francesco-hayes** [comment]
I got it working by switching to Chrome and starting the watcher for the token refresh first. Thank you! I assume that Brave's ad blocker kept getting in the way.
