### ISSUE TITLE
[Auth SSR ServerLogin] Improvements & Fix for Firebase Functions 

### ISSUE THREAD

**Issue by lupas** [nuxt-community/firebase-module#123]
## Description
As mentioned in https://github.com/nuxt-community/firebase-module/pull/121#issuecomment-599260580, the Firebase Authentication SSR serverLogin functionality still has some drawbacks.

- Might need some QPS limits adjustments
- Does not work properly with deployment on Functions SSR (service worker is unable to resolve SSR requests)

## ToDo

- [x] Adjust SSR server login implementation _or_ update the docs accordingly after hearing back from Firebase about **QPS limits for client SDK authentication** (@mentAl-maZe)
- [x] Find a way to make it work with Firebase Functions SSR deployment

**Comment by mentAl-maZe** [comment]
@lupas I have heard back from firebase about the QPS limits, but have not yet found the time to implement a corresponding rate limiter, will use this thread to keep you up to date

**Comment by lupas** [comment]
> @lupas I have heard back from firebase about the QPS limits, but have not yet found the time to implement a corresponding rate limiter, will use this thread to keep you up to date

Great thanks! :) Can you let us now the QPS limits here so we have it documented in this thread?

**Comment by mentAl-maZe** [comment]
The base limit is 20 QPS / IP and a couple dozen logins per user per 10 minutes, but it’s subject to change as needed, without notice.

**Comment by mentAl-maZe** [comment]
Hi @lupas 

Sry for the delay, had to set aside some time to dive into `@nuxt/core`...

But I finally realize my mistake: :man_facepalming: 
`addServerMiddleware` adds a middleware to the nuxt internal connect server.
When setup with firebase functions I use Nuxt as a server middleware for the firebase express server.
Server Middleware is skipped because it was never registered with this server.

As I see it we have 2 possibilities:
- Provide a separate middleware function which can be used with different connect based server frameworks (connect, express, ...)
- Use a plugin (`mode: 'server'`) instead of a middleware to extract the bearer and resolve the user

I personally would go for the plugin solution as it gets cooked into the build and is easily transferable to any server which accepts connect based `(req, res, next)` middlewares.

**Comment by mentAl-maZe** [comment]
See pull request #136 for my proposition

**Comment by lupas** [comment]
Thanks @mentAl-maZe , released with [v5.0.5](https://github.com/nuxt-community/firebase-module/releases/tag/v5.0.5)
