### ISSUE TITLE
Wrong example on doc

### ISSUE THREAD

**Issue by cabelotaina** [nuxt-community/firebase-module#152]
Hi I used this example on my project:

> https://github.com/nuxt-community/firebase-module#quick-config

```modules: [
    [
      '@nuxtjs/firebase',
      {
        config: {
          apiKey: '<apiKey>',
          authDomain: '<authDomain>',
          databaseURL: '<databaseURL>',
          projectId: '<projectId>',
          storageBucket: '<storageBucket>',
          messagingSenderId: '<messagingSenderId>',
          appId: '<appId>',
          measurementId: '<measurementId>'
        },
        services: {
          auth: true // Just as example. Can be any other service.
        }
      }
    ]
  ],
```

But if I put this config in modules the server don't start. Only if I put the config on buildModules.

Is this correct?

**Comment by lupas** [comment]
@cabelotaina 
That must be something about your setup or mistake in how you set it up, because this should work as documented.

Anyway, if it works in `buildModules` it should also work in `modules`.

But good thing you brought this up:
I'll check if we can advise in the documentation for using `buildModules` generally, since in standard cases we don't register any middlewares (anymore). Gotta read into (buildModules docs)[https://nuxtjs.org/guide/modules/#build-only-modules] and make some tests for that.

**Comment by lupas** [comment]
Closing since no answer,.

**Comment by vonec** [comment]
FATAL  Module @nuxtjs/firebase not found.                                                                    02:57:15

  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:182:17)
  at node_modules\@nuxt\utils\dist\utils.js:1803:43
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:43:5)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:685:5)


   ╭─────────────────────────────────────────────────╮
   │                                                 │
   │   ✖ Nuxt Fatal Error                            │
   │                                                 │
   │   Error: Module `@nuxtjs/firebase` not found.
