### ISSUE TITLE
How to get download url from storage

### ISSUE THREAD

**Issue by Scaalees** [nuxt-community/firebase-module#168]
When using the below I'm getting an error due to `XMLHttpRequest is not defined`.

```
this.$fireStorage.ref().child(image[0]).getDownloadURL().then((url) => {
...
});
```

I've tried installing `xmlhttprequest` as a global plugin with nuxt but still getting the same error.

Just wondering if I'm missing something here

**Comment by lupas** [comment]
This doesn't seem like a nuxt/firebase specific issue.

What is the value of image[0]? It should be a string path to the image.

Example:
```js
let ref = this.$fireStorage.ref().child(`items/foo/fuu/image.png`)
const url = await storageRef.getDownloadURL()
```
works for me.

**Comment by Scaalees** [comment]
Hi,

Thanks for that, `image[0]` is returning a string `images/test-01.jpg` which is the ref in firebase storage.

I can get the image url within mounted on my page, but I would ideally want the data to be returned when I'm getting all the firestore (within vuex to store in the state).

Something like below:
```
async setStore({ dispatch, commit }) {
  let tempItems = [];

  await this.$fireStore.collection('items').get().then((querySnapshot) => {
    querySnapshot.forEach((doc) => {
      // Get firebase image url here with doc.data().image[0] (image/test-01/jpg)
      tempItems.push({id: doc.id, ...doc.data()});
    });
  });

  commit('STORE_ITEMS', tempItems);
},
```

Sorry if this more help than an issue.

**Comment by lupas** [comment]
@Scaalees 
As far as I know the Firebase Storage API is not fully compliant with Node, so you seem to run into this issue because you run it on the server with Nuxt.

What you do does not seem very efficient. If I were you, I would save the downloadUrl to Firestore every time you upload an image.

So:

1. Upload image
2. Save url to Firestore "item" into e.g. `item.imageUrl`

Now you always have the URL to the image on the item and query your items MUCH more efficiently. Think about it.

**Comment by Scaalees** [comment]
Fair enough. Wasn't aware of the Storage API not fully working with Node.

Yeah, that method does work a lot better. 

Thanks for the help.
