### ISSUE TITLE
How to get data message from fcm? 

### ISSUE THREAD

**Issue by algoth** [nuxt-community/firebase-module#200]
I have setup fcm messaging using nuxt firebase on the client & firebase-admin and am able to send and receive notifications. 🙌

But I am not able to figure out how to get the info from the data message on page load after the click of notification? 

Any edits I make to firebase-messaging-sw.js get overwritten as it is generated again on server start. Where to use the onMessage() function?

**Comment by lupas** [comment]
Hey @algoth 

Sorry for the late response. First of all, glad it works for you.

We just changed how the serviceWorker behaves with v6.0.0, you are now supposed to work with the HTML v1 API as mentioned in the Firebase documenatation [here](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages).

Since we changed a lot and it's been a while, I will close this issue. Please try to set it up again following our [documentation](https://firebase.nuxtjs.org/guide/options/#messaging) and if you still run into issues feel free to open another issue again.

PS:
If you want to create your own firebase-messaging-sw.js or make additional changes to it, simply set `createServiceWorker = false` and implement it yourself. In case you have special needs for the service worker I think this is the best approach anyway.
