### ISSUE TITLE
Is there a way to open different firebase projects using code

### ISSUE THREAD

**Issue by andyfensham** [nuxt-community/firebase-module#276]
I have an admin site that need to depending on the user that logs in, then need to do all firebase actions on his own firebase project that his user name points to.  I see you allow for different firebase sites like for e.g. production, dev etc, but how would I, depending on the logged in user, attach to that user's firebase project programatically.

**Comment by lupas** [comment]
Hey @andyfensham 

At this point this is not possible with this module. For such advanced use-cases we advice you to implement Firebase manually.

**Comment by automotola** [comment]
If you make a new firebase database, in the **same** project, perhaps this helps might help. In this issue, he shows how you can access a different firebase database within the same project. I know it's not exactly the same, but it might allow you to implement what you were going for but within the same project. I would also require a paid subscription though, since you can't make multiple firebase databases with the default (free) plan.

https://github.com/nuxt-community/firebase-module/issues/288
