### ISSUE TITLE
photoURL is not accessible in SSR

### ISSUE THREAD

**Issue by NoahCardoza** [nuxt-community/firebase-module#319]
### Version
@nuxtjs/firebase: ^6.1.1
firebase: ^7.22.1
nuxt: ^2.14.5

### Reproduction Link
N/A. I might just be dumb.

### Steps to reproduce

1. Use SSR mode
2. Load image
    ```vue
     <img :src="$store.state.user.photoURL" />
     ```

### What is Expected?

An image to be rendered.

### What is actually happening?

The image tag is being created like `<img />` because `photoURL` is `undefined` on the server side.

### Question

Is it possible I miss-configured the SSR?

# P.S.

After a little testing it seems that the problem is rooted in only`uid`, `email`, `emailVerified`, and `displayName` being passed to my `onAuthStateChangedAction`.

**Comment by NoahCardoza** [comment]
Turns out I am dumb, I just read the comment in the example:
> results in photoURL being undefined for server auth

Is there any way around this? Is the best option a simple `v-if`?

**Comment by lupas** [comment]
Hey @NoahCardoza 

Sorry for the late response. If you use the [credential](https://firebase.nuxtjs.org/service-options/auth#credential) options the photoURL should be available in the user object.

Otherwise there is no way around it, other than saving the avatar url in a user object e.g. in Firestore or the Realtime Database. But in this case you would have to load the user object on client-only (i.e. wrap the image in <client-only> tags) and can't render it on the server or statically.

**Comment by thewhtrabbt22** [comment]
This is very frustrating... it's recommended that we don't have access to that field in production apps? Profile photos are very basic functionality.
