### ISSUE TITLE
how to change and listen user email/password/emailVerified directly?

### ISSUE THREAD

**Issue by szczynk** [nuxt-community/firebase-module#378]
Hello, i tried update email using `this.$fireAuth.currentUser.updateEmail(this.newEmail)` but did not change directly, it need to be refresh page. 

Based on this [documentation](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onauthstatechanged), it is only triggered on sign-in, sign-out, or in my case, refresh page. 

Is there any option that change onAuthStateChanged() function to be onIdTokenChanged() function when generate .nuxt/firebase-module/initAuth.js so i can change and listen user email/password/emailVerified directly?

i'm so sorry if my english is broken
thank you very much

**Comment by lupas** [comment]
Hey @szczynk 
Updated auth user data does not get automatically pushed to the client and does not trigger "onAuthStateChanged", because the auth state itself has not changed. You can do the following to refresh the auth user on your client:

```js
 try {
        await this.$fire.auth.currentUser.updateEmail('newEmail@email.com')
        // Reload the user
        this.$fire.auth.currentUser.reload()
        // Now you can get the updated user like so
        const updatedUser = this.$fire.auth.currentUser
        // And then manually save the infos to the vuex store or wherever you like
      } catch (e) {
        console.error(e)
      }
```

Btw: `$this.fire.auth` is syntax for moudule v7.0.0+, make sure to update to the newest version :)

**Comment by szczynk** [comment]
thank you so much for the alternative @lupas :+1: 
i will try migrate from v6 to v7 :)
