### ISSUE TITLE
Firebase Auth SSR stops working after functions is added

### ISSUE THREAD

**Issue by hilmerx** [nuxt-community/firebase-module#528]
I've set up a Nuxt-project with SSR and Firebase as in the guides in the documentation. 

Everything's working just fine until I add Firebase Functions to my nuxt.config.js, at that point, no matter which settings I use in the Functions config, "onAuthStateChangedAction" is called client side with  {authUser: null, claims: null } but is set correctly server side.

How do I work around this or fix this problem?

**Comment by GanchoDanailov** [comment]
that's because the object coming from the function is different
<img width="955" alt="Screenshot 2021-05-20 at 10 41 46" src="https://user-images.githubusercontent.com/6190969/118939094-03fb6600-b958-11eb-83f6-bb12790bcbe4.png">

but the question here is why the mutation is calling 2 times once on the server and once on the client?

**Comment by tibs245** [comment]
The onAuthStateChangedAction is setted to null after refresh page ?

Supposed bug: https://github.com/nuxt-community/firebase-module/issues/465

**Comment by lupas** [comment]
No answer from author for 3 weeks, closing the issue.
