### ISSUE TITLE
Missing res.locals on hard refresh (SSR auth)

### ISSUE THREAD

**Issue by GanchoDanailov** [nuxt-community/firebase-module#530]
### Version
@nuxtjs/firebase: 7.5.0
@nuxtjs/pwa: 3.3.5
firebase: 8.6.1
nuxt: 2.15.3

### Reproduction Link
https://codesandbox.io/s/test-758x2?file=/store/index.js:584-594
https://758x2.sse.codesandbox.io/

### Steps to reproduce
login -> hard refresh the page (Chrome mac - Cmd Shift R) -> missing res.locals on server. (On soft refresh res.locals are ok)

### What is Expected?
On hard refresh - Expecting res.locals on the server

### What is actually happening?
missing res.locals on the server on hard refresh
<img width="30%" alt="soft-refresh" src="https://user-images.githubusercontent.com/6190969/118936354-250e8780-b955-11eb-9db3-672e749490ee.png">
<img width="30%" alt="hard-refresh" src="https://user-images.githubusercontent.com/6190969/118936344-23dd5a80-b955-11eb-9f2b-4a23ccf78d6a.png">

**Comment by GanchoDanailov** [comment]
any update on this? Could you please confirm its known issue

**Comment by lupas** [comment]
Hey @GanchoDanailov 

This is expected.

When you shift-reload, the reloaded page will not be controlled by a service worker. This is part of the [service worker specification](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#shift-reload).

So you won't be able to have server side authentification when a user uses shift-reload -> because no service worker can get the auth credentials and send them to the server before pageload.

If you have onAuthStateChanged configured however, the user gets logged in right afterwards in such a case.

Like you can see here: https://nuxt-fire-demo.herokuapp.com/
