### ISSUE TITLE
Using Firebase Authentication on server-side (SSR) / Nuxt Universal Mode

### ISSUE THREAD

**Issue by lupas** [nuxt-community/firebase-module#69]
This issue is here for...
- collecting insight, approaches and use-cases for achieving SSR with Firebase auth.
- As a reminder to eventually create either a working demo, documentation or helper function that could be delivered within nuxt-fire.

**Comment by lupas** [comment]
With [v3.4.0](https://github.com/lupas/nuxt-fire/releases/tag/v3.4.0) we added the feature to check on server-side, whether the user is authenticated or not, see [documentation](https://nuxtfire.netlify.com/advanced/#firebase-auth-in-universal-mode).

This already makes it possible to:
- [X] Receive authenticated JWT & authUser object (uid, email, email_verified, etc.) on the first request to the server.

What is still missing is:
- [ ] Verify the token on server-side against Firebase (check if it is valid)
- [ ] Log-in the user on server-side (or add auth credentials to other services), so that secure user data can be loaded from server-side e.g. through Firestore

If anyone has any idea on how to achieve that, feel free to share :)

**Comment by lupas** [comment]
Managed to verify the idToken on serverSide in a serverMiddleware and then send the verified authUser to the nuxtServerInit action for processing. So that works will, see [here](https://github.com/lupas/nuxt-fire/tree/843f90e17d185d01aac5283aee9b5bbb0e9597a1).

Problem now is that the idToken is only valid for 1 hour and generating a refreshToken would have to be done on client-side, which is not possible before the first request EXCEPT this would be done in a service-worker, as outlined here in the official [Firebase Docs](https://firebase.google.com/docs/auth/web/service-worker-sessions).

That article actually summarises the problems quite well. I'll see if I can get the service-worker approach to work in nuxt-fire next.

**Comment by lupas** [comment]
With [v3.5.1](https://github.com/lupas/nuxt-fire/releases/tag/v3.5.1) I introduced the `auth.initialize.ssr = true` option which verifies the auth user on server-side.

The verified `authUser object` and `idToken` is then available on the server in the `nuxtServerInit` action.

Remaining:

- [ ]  Log-in the user on server-side (or add auth credentials to other services), so that secure user data can be loaded from server-side e.g. through Firestore

**Comment by mentAl-maZe** [comment]
First off, thank you for this awesome module :smile:
 
This seems mostly resolved, i'd like to add my 2 cents though :sweat_smile: 

# Use-Case
A universal nuxt app fully hosted on firebase services (hosting, functions).

# Issues
1. I'd like to be able to wait for the authentication to fully finish before i redirect the user to a protected route, but i have no possibility to hook into the `onSuccessAction`
2. I'd like to be able to reuse my user object on the server side (i.e. reuse my `onSuccessAction` to hydrate the store on the server)

# Approach
## Issue 1
I don't use the modules `services.auth.initialize` option (I would like to be able to use the `ssr` option though, see **Issue 2**), because i don't want to trigger my initialization action every time the auth state changes.
Instead i split the authorization into
* a client side init where i unsubscribe from the listener immediately

and

* a login action

which both call the `onSuccessAction`

**plugins/nuxtClientInit.ts:**

```typescript
import { Plugin } from '@nuxt/types'
import { logRequest } from '~/assets/helpers'

const nuxtClientInit: Plugin = async ctx => {
  await logRequest(
    () => ctx.app.$fireStore.enablePersistence(),
    'firestore:persistence'
  )
  await ctx.store.dispatch('nuxtClientInit', ctx)
}

export default nuxtClientInit
```

**store/backend.ts**

```typescript
export const actions: ActionTree<State, RootState> = {
  // ...
  async nuxtClientInit({ dispatch }) {
    const authUser = await new Promise(
      (resolve: (user: FireUser | null) => void) => {
        const unsubscribe = this.$fireAuth.onAuthStateChanged(user => {
          unsubscribe()

          resolve(user)
        })
      }
    )

    if (authUser) {
      const { claims } = await authUser.getIdTokenResult()
      await dispatch('onAuthSuccess', { authUser, claims })
    }
  },
  // ...
  async login({ state, dispatch }, { email, password, remember }) {
    if (!remember) {
      await this.$fireAuth.setPersistence(
        this.$fireAuthObj.Auth.Persistence.SESSION
      )
    }

    const { user: authUser } = await this.$fireAuth.signInWithEmailAndPassword(
      email,
      password
    )

    if (authUser) {
      const { claims } = await authUser.getIdTokenResult()
      await dispatch('onAuthSuccess', { authUser, claims })
    }

    return state.user
  },
  // ...
}
```

## Issue 2
I don't use the modules `services.auth.initialize.ssr` setting because I don't want the `onAuthStateChanged` listener to be set permanently, but I have reproduced it's functionality using `@nuxtjs/pwa`s `workbox.importScripts` setting and an `auth-sw.js` in the `static` directory.

On the server side I don't use the modules implementation, but a server side plugin (`{ mode: 'server' }`) which calls my `backend/onAuthSuccess` action upon reconstructing a user from the auth header.
The [`admin.auth.UserRecord`](https://firebase.google.com/docs/reference/admin/node/admin.auth.UserRecord) returned by [`admin.auth.Auth.getUser(uid)`](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth.html#getuser) is sufficiently similar to the [`firebase.User`](https://firebase.google.com/docs/reference/js/firebase.User) object to be able to recover all user properties I require in my `backend/onAuthSuccess` action.

```typescript
import { Plugin } from '@nuxt/types'

import { auth } from '~/assets/firebase/admin'
import { logRequest } from '~/assets/helpers'

const fireAdminAuth: Plugin = async ({ req, store }) => {
  if (!req.headers.authorization) return

  const authorizationHeader = req.headers.authorization || ''
  const components = authorizationHeader.split(' ')
  const idToken = components.length > 1 ? components[1] : ''

  const claims = await logRequest(() => auth.verifyIdToken(idToken))
  if (claims) {
    const authUser = await logRequest(() => auth.getUser(claims.uid))

    await store.dispatch('backend/onAuthSuccess', { authUser, claims })
  }
}

export default fireAdminAuth
```

**Comment by lupas** [comment]
Hi @mentAl-maZe 

Some comments and question regarding your issues and approach.

## Regarding Issue 1
> I'd like to be able to wait for the authentication to fully finish before i redirect the user to a protected route, but i have no possibility to hook into the onSuccessAction

You define the onSuccessAction **yourself** and merely link to it with the onSuccessAction string. So there is no "hook" you could hook into.

In your action you can do asynchronously whatever you want, e.g. load user data or save the user object to the store. After that in your `middleware` you can access the authUser object before routing like so:

```js
export default function({ store, redirect }) {
  const authUser = store.state.authUser
  // redirect if user is null or not null
}
```

And for SSR, if you use the SSR option and set the authUser in `nuxtServerInit` accordingly, you also have the authUser accessible in your middleware before routing.

So this case should work already.

## Regarding Issue 2
> I'd like to be able to reuse my user object on the server side (i.e. reuse my onSuccessAction to hydrate the store on the server)

For your case, wouldn't something like this work?

```js
// in nuxt-config
onSuccessAction: 'setAuthUser'

// in store
setAuthUser({ commit }, { authUser }) {
  commit('SET_AUTH_USER', { authUser })
},

yourServerAction({ dispatch }, { authUser }) {
  // whatever your server action is doing
  dispatch('setAuthUser', { authUser })
},
```
Since this is rather an edge case, I'm not sure if that makes sense to implement in the plugin.

---

>  i don't want to trigger my initialization action every time the auth state changes.
Why exactly is that? Just create a separate onSuccessAction that has only the relevant code for authStateChanges, don't put other code in there that you want not to be triggered.

Instanciate firebase-admin with the config works btw, at least for what the serverMiddleware is doing.

These comments just based on your "issue" description and not your approaches, haven't had enough time to go through the code thoroughly. Let me know if I missed something you want to achieve or if I totally missed the point. :)

**Comment by mentAl-maZe** [comment]
Thanks for your reply

Here are some further thoughts on the issues

# Regarding Issue 1

The problem is not on initialization where the application awaits the completion of the `onAuthStateChange` handler and consequently the `onAuthSuccess` action, but when logging in a user where I'd like to be able to await completion of the `onAuthSuccess` action without employing arbitrary waiting mechanisms (e.g. `setTimeout`) before redirecting the user to an admin route.

If i redirect the user before the `onAuthSuccess` action has completed the `authUser` is not yet updated in the store and a middleware checking for it will fail and redirect my user back to the login screen.

By **hook into** i mean to hook into the `onAuthStateChange` handler, more precisely, to determine when it has completed.

## Implemented solution

I map the `store.state.backend.user` onto a `user` property in the `LoginPage` component and watch that property for updates:

```ts
export default class LoginPage extends mixins(HasValidationForm) {
  
  // ...
  
  @backend.State readonly user!: State['user']
  
  // ...
  
  @Watch('user')
  async onUserUpdate(user?: User) {
    if (user) {
      if (
        user.claims.admin &&
        (user.settings.client === 'admin' || !user.claims.clients.length)
      ) {
        this.$router.push(this.localePath('admin'))

        return
      } else if (user.claims.clients.length) {
        const client =
          user.settings.client &&
          user.claims.clients.includes(user.settings.client)
            ? user.settings.client
            : await this.clients.select(user.claims.clients)

        this.$router.push({
          name: 'admin-client',
          params: {
            client
          }
        })

        return
      }
    }

    await this.logout()

    this.showAlert(error('No client', 'no-client'))
  }

  // ...

}
```

## Remaining issue

It would be nice to get the `authUser` in the `onSuccessAction` even if it resolves to `null`, or alternatively be able to specify another Action/Mutation for that case, so i can handle logout.

# Regarding Issue 2

Once i was able to implement login using your plugin (see **Issue 1**), i was able to use the `ssr` flag in the options of your module and to resolve this similarly to how you proposed in your reply

**Comment by lupas** [comment]
@mentAl-maZe 
### Regarding Issue 1
In my opinion this is exactly how onAuthStateChanged() **should** be handled. User watchers is imho the best way to go when working with Firebase AuthUser. That's how I do it:

```js
export default {
  computed: {
    ...mapState({
      authUser: (state) => state.user.authUser
    }),
    isAuthenticated() {
      return this.authUser !== null
    }
  },
  watch: {
    isAuthenticated(val) {
      if (this.isAuthenticated) {
        this.goToSecuredView()
      }
    }
  },
  beforeMount() {
    if (this.isAuthenticated) {
      this.goToSecuredView()
    }
  },
  methods: {
    goToSecuredView() {
      this.$router.push('/user/welcome')
    }
  }
}
```

Of course your login action that logs in the user belongs somewhere.

And if you want to show a loader or anything when a user clicks on login, just set `this.loading = false` in the isAuthenticated watcher.

I think it is a more elegant solution to watch the authUser than trying to hook into onAuthStateChanged().

But... I'll think about adding a hook to it if I really see the benefit of it, I'll have a further look at it a bit later.

### Regarding Remaining issue
You can set `immediate: true` in a watcher to get it triggered on immediately.
```js
  watch: {
    isAuthenticated: {
      immediate: true,
      handler(val) {
          if (this.isAuthenticated) {
            this.goToWelcomeScreen()
          }
    }
  },
```

> Also: It would be nice to get the authUser in the onSuccessAction even if it resolves to null, or alternatively be able to specify another Action/Mutation for that case, so i can handle logout.

This probably make sense, yes. I'll have a look at it :)

> This might come down to personal preference, but i feel the verifiedFireAuthUser object should be set on the req instead of the res object

Same :) Thanks!

**Comment by reskume** [comment]
Hi,

hope this is the place to ask and if not feel free to remove this but is there a possibility to get custom user claims from "ctx.res.verifiedFireAuthUser" on server side or do I have to implement my own serverMiddleware? Custom user claims are especially useful when used as RBAC for example, e.g. "role" claim.

Cheers and thanks,

Stephan

**Comment by lupas** [comment]
@reskume

You couldn't, but your comment lead to [v3.5.4](https://github.com/lupas/nuxt-fire/releases/tag/v3.5.4) and now you can :-) Just use `ctx.res.verifiedFireAuthUser`.

See Updated Documentation:
https://nuxtfire.netlify.com/tutorials/ssr/

**Comment by reskume** [comment]
@lupas 

Great news! Thanks and a happy new year!

**Comment by ivaaaan** [comment]
I'm authenticating a user using this method: https://firebase.nuxtjs.org/tutorials/ssr/
But it turns out that I cannot query the Firestore on the server-side(fetching data in `async` method):  `Missing or insufficient permissions.` 

Anyone had this issue before? Querying the Firestore on the client-side is working perfectly.

**Comment by lupas** [comment]
Hi @ivaaaan 

This functionality is not yet built into this module. See the open point further above:

> Missing
> - [ ] Log-in the user on server-side (or add auth credentials to other services), so that secure user data can be loaded from server-side e.g. through Firestore

As of now, you can get the verified `authUser` object from the server, but you cannot do authenticated calls e.g. to Firestore on server-side. That's still an open point.

I created a [new issue](https://github.com/nuxt-community/firebase-module/issues/117) for that in favour if this one, to make it clear that we'll have to work on this specific feature, since this thread is not that specific.

**Comment by lupas** [comment]
Closed in favour of https://github.com/nuxt-community/firebase-module/issues/117 .
