### ISSUE TITLE
Investigate: Possibility to use nuxt-fire in ServerMiddleware

### ISSUE THREAD

**Issue by lupas** [nuxt-community/firebase-module#9]
### Problem
ServerMiddleware are ran before executing Nuxt render. So there is currently no way to access the context and therefore nuxt-fire in a ServerMiddleware (as is the case with any other module).

If for some reason someone wants to use Firebase in a ServerMiddleware (e.g. dynamically rendering a sitemap outside of nuxt.config.js), one would have to initialize Firebase separately only for the ServerMiddleware.

This use case is rare, but it so happens to exist.

### Solution
unclear - investigate

**Comment by lupas** [comment]
Over two years of inactivity, seems not to be important at this point. Will reopen if it ever comes up.

**Comment by rolandszpond** [comment]
I'm currently trying to figure this out. I'm trying to build some api endpoints using serverMiddleware but when trying to admin.initializeApp it throws and error that it's being called multiple times, even when checking !admin.apps.length

**Comment by Flawe** [comment]
@lupas 
I might have a need for something like this:

I have auth ssr enabled and a serverMiddleware with an endpoint that makes a query on a SQL database. I want this query to be restricted to rows owned by the logged in user (i.e. the rows should have a column with the user's uid). Which means I need a secure way of knowing the currently logged in user's uid in my serverMiddleware.

If I understand things correctly, because serverMIddleware runs first, we don't have access to the decoded token (no res.locals populated yet). Is my only option to pass the token from the client with the call to the serverMiddleware endpoint, and decode the token manually there? Are there other options?

**Comment by ankurgla22** [comment]
Is there any update on it? 
I want to use APIs for the firebase store so I want to use nuxt-fire in ServerMiddleware
